version: 2.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image:
- macOS
- Ubuntu2004
- Visual Studio 2019
platform: x64
environment:
  GH_TOKEN:
    secure: nzUU8F4CLe1EDxmKabW5Ym6NnL0SEK+VLft2D8oh72KEcfejyt1xWsQq9dMg6Wpt
before_build:
- pwsh: dotnet restore
build:
  parallel: true
  verbosity: minimal
after_build:
- pwsh: ./publish-github-release.ps1
artifacts:
- path: Publish\*.zip
  name: zip
deploy:
- provider: GitHub
  release: Continious build
  description: Information about changes since previous release can be found in [changelog](https://github.com/Gigas002/DoujinDownloader/blob/master/CHANGELOG.md).
  auth_token: $(GH_TOKEN)
  artifact: /.*\.zip/
  prerelease: true
  force_update: true
  on:
    branch: master
after_deploy:
- pwsh: ./publish-github-docker.ps1 $env:GH_TOKEN $env:APPVEYOR_BUILD_WORKER_IMAGE