//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoujinDownloader.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoujinDownloader.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t parse {0}:{1}.
        /// </summary>
        internal static string CantParse {
            get {
                return ResourceManager.GetString("CantParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done in hours:{0}, minutes:{1}, seconds:{2}, milliseconds:{3}..
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doujins count:{0}.
        /// </summary>
        internal static string DoujinsCount {
            get {
                return ResourceManager.GetString("DoujinsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doujins to download count:{0}.
        /// </summary>
        internal static string DoujinsToDownloadCount {
            get {
                return ResourceManager.GetString("DoujinsToDownloadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option -i/--input is not set..
        /// </summary>
        internal static string InputNotSet {
            get {
                return ResourceManager.GetString("InputNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -i/--input file extensions is not {0}/{1}.
        /// </summary>
        internal static string InputWrongExtension {
            get {
                return ResourceManager.GetString("InputWrongExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -j/--json file extensions is not {0}.
        /// </summary>
        internal static string JsonWrongExtension {
            get {
                return ResourceManager.GetString("JsonWrongExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No doujins selected in {0} file..
        /// </summary>
        internal static string NoDoujinsInInput {
            get {
                return ResourceManager.GetString("NoDoujinsInInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not supported.
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -u/--uris file extensions is not {0}.
        /// </summary>
        internal static string UrisWrongExtension {
            get {
                return ResourceManager.GetString("UrisWrongExtension", resourceCulture);
            }
        }
    }
}
